### ISSUE TITLE
Add ability to override default thumbnail URL

### ISSUE THREAD

**Issue by dgutman** [dgutman/webix_image_organizer#130]
For multi-frame images, the default thumbnail often appears as black which is not very visually appealing.  In the faceted search and image organizer viewers, please add a configuration option where it will look in

item.meta.htanMeta.defaultImgThumbUrl  

Make the actual "spot" it looks relatively easy to edit... I may not always append it to htanMeta, but may use a different metadata element.

For this usecase, whatever string is in the defaultImgThumbUrl needs to just be appended to the "base" thumbnail URL.   The DSA/largeImage recently added the ability to render multiple frames with styling... 

So I'd much rather look at this version:
![image](https://user-images.githubusercontent.com/713166/117912168-00f3dc00-b2ad-11eb-9e68-18d7e392f7a9.png)

vs this:
![image](https://user-images.githubusercontent.com/713166/117912252-2d0f5d00-b2ad-11eb-8a89-da4c60feae4b.png)

Normally for an item, we retrieve the thumbnail by hitting an address like this:
api/v1/item/#_id#/tiles/thumbnail

if we add something similar to the following, we basically tell the system to grab frames 0, 1 and 2... color frame 0 blue, from 1 green, and frame 2 red... and this also sets the min/max automatically.

On the faceted search side of things, all we need to do is look to see if item.meta.htanMeta.defaultImgThumbUrl is set, and if so append whatever JSON string to the calling URL.

                    template: "<img src=https://imaging.htan.dev/girder/api/v1/item/#_id#/tiles/thumbnail?frame=0&style=" +
                        encodeURIComponent(JSON.stringify({
                            bands: [{
                                palette: ['#000000', '#0000ff'],
                                max: "auto"
                            }, {
                                frame: 1,
                                palette: ['#000000', '#00ff00'],
                                max: "auto"
                            }, {
                                frame: 2,
                                palette: ['#000000', '#ff0000'],
                                max: "auto"
                            }]
                        })) + " ></img>"

**Comment by jvizcar** [comment]
@dgutman has this been resolved?
