### ISSUE TITLE
Not retrieving all the folders

### ISSUE THREAD

**Issue by dgutman** [dgutman/webix_image_organizer#21]
Only retrieving the first 50 folders... need to eventually get them all... the 50 is the default returned for the "folder" endpoint..

Can test in DermAnnotator-->ISIC_ARCHIVE-->LesionImages  and of those folders (MSK-1 for example) has 50+ folders.. it's only returning the first 50.  Good news htough--- check out the reponseHeaders-- when querying either for items or folders, there is now a new element in the resopnse header, girder-total-coutn that returns the total number of items (or folders) under than hierarchy-- this should allow us to more easily paginate/scroll through stuff, since we know the total item count now..

{
  "date": "Tue, 12 Mar 2019 00:54:50 GMT",
  "girder-total-count": "21462",
  "server": "Girder 2.5.0",
  "content-length": "21810",
  "allow": "DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT",
  "content-type": "application/json"
}

![image](https://user-images.githubusercontent.com/713166/54167367-bca3f180-443f-11e9-8977-d09f17fdfdb6.png)

![image](https://user-images.githubusercontent.com/713166/54167427-0096f680-4440-11e9-9c87-7d8a1383a514.png)

**Comment by dverkhovsky13** [comment]
This is deafult server behaviour for GET/folders request. As you can check, there is no additional query params has been send to the server for getting only first 50. We can't use 'total-count' in response headers for first request bc it's comming to us after server code has been initiated, so basically we need to send other request which is not good at all. You need to fix you server code so we should be able to get all folders we need with only GET/folders request

**Comment by dgutman** [comment]
Dimitry--- I think we need to change the default to pull more than fifty-- this can be passed as a parameter--  since a folder can have 1000+++ items in it, we don't want to get everything.. but 50 is probably to small...
Can we change the default to 500, and also after you get those items, use the total-count from the response header to update the folder name with like ADRC-50-1(500/100000)  and then maybe we add some right click behavior to either get all the folders and/or we create a pager to allow us to scroll through them
