### ISSUE TITLE
not returning anything on computablebrain..

### ISSUE THREAD

**Issue by dgutman** [dgutman/webix_image_organizer#22]
tried to connect to computablebrain and access the FOX_DATA collection-- seems like it's pullkng the item data, but the UI isn't updating..

**Comment by dgutman** [comment]
aaah-- i think something is weird.
it looks like it's not using the correct SERVER Address.... I had first logged onto dermannotator, and then switched servers for testing..

![image](https://user-images.githubusercontent.com/713166/54167600-ec072e00-4440-11e9-968f-195992147903.png)

**Comment by dverkhovsky13** [comment]
Could you share your code that you write for new server? I can't say where problem is with only a screenshot.

**Comment by dverkhovsky13** [comment]
Have you switched to 'candygram' host? Because I don't remember any "Computable Brain" hosts.
