### ISSUE TITLE
Loggedin user not getting changed ever after switching over host

### ISSUE THREAD

**Issue by sraja2911** [dgutman/webix_image_organizer#26]
Once logged in with user with specific host (cancer digital slide archive), when try to change to different host (eg: computablebrain), user not getting logged out with previous host. 

User logging out and host switching is not clean. Still it maintains the previous user with old host, despite changing to new host.

**Comment by dverkhovsky13** [comment]
Could you please tell me what's a 'computable brain' host? And once you logged-in in both hosts and didn't clean your localstorage you will be logged-in every time you switch a host. Just checked it with cleared localStorage and everything works.
