### ISSUE TITLE
new testing server

### ISSUE THREAD

**Issue by dgutman** [dgutman/webix_image_organizer#28]

**Comment by dgutman** [comment]
Please check out Girder--> ISIC_MIRROR --> LesionImages --> MSK-(any)

![image](https://user-images.githubusercontent.com/713166/54529362-116ecd00-4956-11e9-98d0-105dd33387fa.png)

Couple of things:

1)  This is only loading the first 50 folders--- this is the default # of folders returned by the API, but if you look at the Response Header, you can see total number of folder objects available, so can use that to build a generator

2)  The metadata isn't showing up in the table..

**Comment by dverkhovsky13** [comment]
1. We can't use total number of folders in one request, cuz it's in Response Header which we are getting after request has been already sent. So if you need to display all folders we should send another request.
2. You can check and see that files with "undefined" metadata value have no metadata at all. "No present metadata" means that there is metadata property in this file, but doesn't have this particular value.

**Comment by dgutman** [comment]
Ok I think we need to discuss this on a google hangout and make sure things are working as they should..

**Comment by dgutman** [comment]
Can we work on retrieving more than 50 filters.. even if we just check the response header and issue a second request to pull more that would be useful... also increasing from a default of 50 to say 500 would probably help with performance/usefulnes
