### ISSUE TITLE
Editing in metadata table

### ISSUE THREAD

**Issue by dgutman** [dgutman/webix_image_organizer#3]
Not sure if the edit feature is working... it is listing UNDEFINED when I try and edit a box... maybe its just not inheriting the current value?

Sample image was taking from FOX_DATA.TODELETE--> CuratedFoxData--> 11T although I think this is a generic issue

![image](https://user-images.githubusercontent.com/713166/51391017-f2db8980-1afe-11e9-813b-833d4fd5a5ab.png)

![image](https://user-images.githubusercontent.com/713166/51391051-07b81d00-1aff-11e9-8c48-d2925b5e23c1.png)

**Comment by sraja2911** [comment]
Looks like now it is editable and getting updated.
