### ISSUE TITLE
add metadata to item from metadata grid view

### ISSUE THREAD

**Issue by dgutman** [dgutman/webix_image_organizer#35]
Currently if an item does NOT had a metadata field, I can’t edit/ add it… it would be very helpful to allow me to edit and save missing fields in this way

We need to be careful in the case of “nested” items that we don’t accidentally delete existing data.

So say we have keys [groups.BRAIN, groups.HEMI and groups.REGION]

If an item had groups.HEMI and groups.BRAIN already populated, but groups.REGION listed “no present metadata”,

![image](https://user-images.githubusercontent.com/713166/57555135-7684e480-7341-11e9-9c68-47427ca19a5f.png)

**Comment by jvizcar** [comment]
Works now, even on the nested meta keys. Closing.
