### ISSUE TITLE
add navigation by cursor keys

### ISSUE THREAD

**Issue by dgutman** [dgutman/webix_image_organizer#37]
please add the following two properties to the metadata table viewer:

1)  Navigation (so I can use the up/down keys to change records)
2) Can we add tooltip:True to the datatable configuration.  Sometimes useful for really long fields..

**Comment by dgutman** [comment]
I see you added the ability to move up/down when I am in edit mode.

This also actually needs to trigger the new row being selected, as I need it to load the new thumbnail/macro/label images so I can "see" what the slides is so I can actually update the metadata.

Ideally if I am not in "edit" mode, it would move up/down and change the selected row;  I do like the ability that when I am editing , that if I click arrow down, I stay in edit mode in the subsequent window as it saves a couple of key presses.



![image](https://user-images.githubusercontent.com/713166/58104405-befa9880-7bb2-11e9-9c40-291bebb88458.png)

**Comment by jvizcar** [comment]
Issue was tested, it is fixed.
