### ISSUE TITLE
selectFilter acting weird..

### ISSUE THREAD

**Issue by dgutman** [dgutman/webix_image_organizer#7]
When I added a select Filter--- it initially worked when I added the columns and was editing the view.. but then when I switched to another folder, it went wonky..

![image](https://user-images.githubusercontent.com/713166/51696465-93381f00-1fd3-11e9-98cc-7c8c6fd7a098.png)

**Comment by dverkhovsky13** [comment]
Fixed in new build. Also you might be able to add new host by changing only one directory "webpack.config.js". There is EnvironmentPlugin which contains SERVER_LIST array. You can change/add new host by adding new object to that array with the same properties as the others.

**Comment by dverkhovsky13** [comment]
Almost forgot. Clear local storage before you're gonna test it.
